//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAtr.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomOptions
    {
        public int RoomOptionsId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Room_RoomId { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
