//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestHookah.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsOnSite
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string ShortDescription { get; set; }
        public System.DateTime ArticleCreationDate { get; set; }
        public string AuthorOfArticle { get; set; }
        public string Content { get; set; }
        public string ArticleImagePath { get; set; }
    }
}
